bolt/src/Asmb/Competition/Entity/Championship.php
<?php

namespace Bundle\Asmb\Competition\Entity;

/**
 * Entity for championship.
 *
 * @author    Perrine Léquipé <perrine.lequipe@gmail.com>
 * @copyright 2019
 */
class Championship extends AbstractShortNamedEntity
{
    /**
     * @var int
     */
    protected $year;
    /**
     * @var boolean
     */
    protected $is_active;

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year)
    {
        $this->year = $year;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $isActive)
    {
        $this->is_active = $isActive;
    }

    public function getFullName()
    {
        $finalName = $this->getName();

        if (strpos($finalName, $this->getYear()) === false) {
            $finalName .= ' ' . $this->getYear();
        }

        return $finalName;
    }
}

bolt/src/Asmb/Competition/Entity/Championship/PoolMeeting.php
<?php

namespace Bundle\Asmb\Competition\Entity\Championship;

use Bolt\Storage\Entity\Entity;
use Carbon\Carbon;

/**
 * Entité pour représenter une rencontre entre 2 équipes.
 *
 * @author    Perrine Léquipé <perrine.lequipe@gmail.com>
 * @copyright 2019
 */
class PoolMeeting extends Entity
{
    const STATUS_NOTIFY_DONE = 1;
    const STATUS_NOTIFY_TODO = 0;

    /** @var int */
    protected $pool_id;
    /** @var string */
    protected $home_team_name_fft;
    /** @var string */
    protected $visitor_team_name_fft;
    /** @var int */
    protected $day;
    /** @var Carbon */
    protected $date;
    /** @var Carbon */
    protected $report_date;
    /** @var boolean */
    protected $is_reported = 0;
    /** @var Carbon */
    protected $time;
    /** @var string */
    protected $result;
    /** @var string */
    protected $club_flag;
    /** @var string */
    protected $matches_sheet_fft_id;
    /** @var array */
    protected $params_fdm_fft = [];

    protected $notify_status = self::STATUS_NOTIFY_TODO;

    // Following properties are not stored in DB, but used as simple object data.
    /** @var string */
    protected $home_team_name;
    /** @var boolean */
    protected $home_team_is_club;
    /** @var string */
    protected $visitor_team_name;
    /** @var boolean */
    protected $visitor_team_is_club;
    /** @var integer */
    protected $championship_id;
    /** @var string */
    protected $championship_name;
    /** @var string */
    protected $championship_short_name;
    /** @var string */
    protected $category_name;
    /** @var string */
    protected $category_identifier;
    /** @var string */
    protected $competition_record_title;
    /** @var string */
    protected $competition_record_slug;
    /** @var Carbon */
    protected $updated_at;
    /** @var bool */
    protected $isWo = false;

    /**
     * @return mixed
     */
    public function getPoolId()
    {
        return $this->pool_id;
    }

    /**
     * @param mixed $pool_id
     */
    public function setPoolId($pool_id)
    {
        $this->pool_id = $pool_id;
    }

    /**
     * @return mixed
     */
    public function getHomeTeamNameFft()
    {
        return $this->home_team_name_fft;
    }

    /**
     * @param mixed $homeTeamNameFft
     */
    public function setHomeTeamNameFft($homeTeamNameFft)
    {
        $this->home_team_name_fft = $homeTeamNameFft;
    }

    /**
     * @return mixed
     */
    public function getVisitorTeamNameFft()
    {
        return $this->visitor_team_name_fft;
    }

    /**
     * @param mixed $visitorTeamNameFft
     */
    public function setVisitorTeamNameFft($visitorTeamNameFft)
    {
        $this->visitor_team_name_fft = $visitorTeamNameFft;
    }

    /**
     * @return mixed
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * @param mixed $day
     */
    public function setDay($day)
    {
        $this->day = $day;
    }

    /**
     * @return Carbon
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param Carbon $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getReportDate()
    {
        return $this->report_date;
    }

    /**
     * @param mixed $reportDate
     */
    public function setReportDate($reportDate)
    {
        $this->report_date = $reportDate;
    }

    /**
     * @return int
     */
    public function getIsReported()
    {
        return (int) $this->is_reported;
    }

    /**
     * @param int $isReported
     */
    public function setIsReported($isReported)
    {
        $this->is_reported = (int) $isReported;
    }

    /**
     * @return mixed
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * @param mixed $time
     */
    public function setTime($time)
    {
        $this->time = $time;
    }

    /**
     * @return mixed
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * @param mixed $result
     */
    public function setResult($result)
    {
        $this->result = $result;
    }

    /**
     * @return mixed
     */
    public function getClubFlag()
    {
        return $this->club_flag;
    }

    /**
     * @param mixed $clubFlag
     */
    public function setClubFlag($clubFlag)
    {
        $this->club_flag = $clubFlag;
    }

    public function getMatchesSheetFftId(): ?string
    {
        return $this->matches_sheet_fft_id;
    }

    public function setMatchesSheetFftId(?string $matchesSheetFftId)
    {
        $this->matches_sheet_fft_id = $matchesSheetFftId;
    }

    /**
     * @return array
     */
    public function getParamsFdmFft()
    {
        return $this->params_fdm_fft;
    }

    /**
     * @param array $paramsFdmFft
     */
    public function setParamsFdmFft(array $paramsFdmFft)
    {
        $this->params_fdm_fft = $paramsFdmFft;
    }

    /**
     * @return string
     */
    public function getHomeTeamName()
    {
        return $this->home_team_name;
    }

    /**
     * @param string $homeTeamName
     */
    public function setHomeTeamName($homeTeamName)
    {
        $this->home_team_name = $homeTeamName;
    }

    /**
     * @return bool
     */
    public function getHomeTeamIsClub()
    {
        return $this->home_team_is_club;
    }

    /**
     * @param bool $homeTeamIsClub
     */
    public function setHomeTeamIsClub($homeTeamIsClub)
    {
        $this->home_team_is_club = (bool) $homeTeamIsClub;
    }

    /**
     * @return string
     */
    public function getVisitorTeamName()
    {
        return $this->visitor_team_name;
    }

    /**
     * @param string $visitorTeamName
     */
    public function setVisitorTeamName($visitorTeamName)
    {
        $this->visitor_team_name = $visitorTeamName;
    }

    /**
     * @return bool
     */
    public function getVisitorTeamIsClub()
    {
        return $this->visitor_team_is_club;
    }

    /**
     * @param bool $visitorTeamIsClub
     */
    public function setVisitorTeamIsClub($visitorTeamIsClub)
    {
        $this->visitor_team_is_club = (bool) $visitorTeamIsClub;
    }

    /**
     * @return integer
     */
    public function getChampionshipId()
    {
        return $this->championship_id;
    }

    /**
     * @param integer $championshipId
     */
    public function setChampionshipId($championshipId)
    {
        $this->championship_id = $championshipId;
    }

    /**
     * @return string
     */
    public function getChampionshipName()
    {
        return $this->championship_name;
    }

    /**
     * @param string $championshipName
     */
    public function setChampionshipName($championshipName)
    {
        $this->championship_name = $championshipName;
    }

    /**
     * @return string
     */
    public function getChampionshipShortName()
    {
        return $this->championship_short_name;
    }

    /**
     * @param string $championshipShortName
     */
    public function setChampionshipShortName($championshipShortName)
    {
        $this->championship_short_name = $championshipShortName;
    }

    /**
     * @return string
     */
    public function getCategoryName()
    {
        return $this->category_name;
    }

    /**
     * @param string $categoryName
     */
    public function setCategoryName($categoryName)
    {
        $this->category_name = $categoryName;
    }
    /**
     * @return string
     */
    public function getCategoryIdentifier()
    {
        return $this->category_identifier;
    }

    /**
     * @param string $categoryIdentifier
     */
    public function setCategoryIdentifier($categoryIdentifier)
    {
        $this->category_identifier = $categoryIdentifier;
    }

    /**
     * @return string
     */
    public function getCompetitionRecordTitle()
    {
        return $this->competition_record_title;
    }

    /**
     * @param string $competitionRecordTitle
     */
    public function setCompetitionRecordTitle($competitionRecordTitle)
    {
        $this->competition_record_title = $competitionRecordTitle;
    }

    /**
     * @return string
     */
    public function getCompetitionRecordSlug()
    {
        return $this->competition_record_slug;
    }

    /**
     * @param string $competitionRecordSlug
     */
    public function setCompetitionRecordSlug($competitionRecordSlug)
    {
        $this->competition_record_slug = $competitionRecordSlug;
    }

    /**
     * @return Carbon
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param Carbon $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    }

    /**
     * @return Carbon
     */
    public function getFinalDate()
    {
        if (null !== $this->report_date) {
            return $this->report_date;
        }

        return $this->date;
    }

    public function setNotifyStatus(?int $notifyStatus)
    {
        $this->notify_status = $notifyStatus;
    }

    public function getNotifyStatus(): ?int
    {
        return $this->notify_status;
    }

    public function isWo(): ?bool
    {
        return $this->isWo;
    }

    public function setIsWo(?bool $isWo)
    {
        $this->isWo = $isWo;
    }
}

bolt/src/Asmb/Competition/Entity/Championship/PoolMeetingMatch.php
<?php

namespace Bundle\Asmb\Competition\Entity\Championship;

use Bolt\Storage\Entity\Entity;
use Carbon\Carbon;

/**
 * Entité pour représenter un match d'une rencontre entre 2 équipes.
 *
 * @author    Perrine Léquipé <perrine.lequipe@gmail.com>
 * @copyright 2022
 */
class PoolMeetingMatch extends Entity
{
    const TYPE_SIMPLE = 'S';
    const TYPE_DOUBLE = 'D';

    /** @var int */
    protected $pool_meeting_id;

    /** @var string */
    protected $type;

    /** @var string */
    protected $label;

    /** @var int */
    protected $position;

    /** @var string */
    protected $home_player_name;

    /** @var string */
    protected $home_player_rank;

    /** @var string */
    protected $visitor_player_name;

    /** @var string */
    protected $visitor_player_rank;

    /** @var string */
    protected $home_player2_name;

    /** @var string */
    protected $visitor_player2_name;

    /** @var string */
    protected $home_player2_rank;

    /** @var string */
    protected $visitor_player2_rank;

    /** @var string */
    protected $score;

    /** @var Carbon */
    protected $created_at;

    /** @var Carbon */
    protected $updated_at;

    /**
     * @return int
     */
    public function getPoolMeetingId()
    {
        return $this->pool_meeting_id;
    }

    /**
     * @param mixed $pool_meeting_id
     */
    public function setPoolMeetingId($pool_meeting_id)
    {
        $this->pool_meeting_id = $pool_meeting_id;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * @return string
     */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * @param string $label
     */
    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * @return int
     */
    public function getPosition(): int
    {
        return $this->position;
    }

    /**
     * @param int $position
     */
    public function setPosition(int $position): void
    {
        $this->position = $position;
    }

    /**
     * @return string
     */
    public function getScore(): ?string
    {
        return $this->score;
    }

    /**
     * @param string|null $score
     */
    public function setScore(?string $score): void
    {
        $this->score = $score;
    }

    /**
     * @return Carbon
     */
    public function getCreatedAt(): Carbon
    {
        return $this->created_at;
    }

    /**
     * @param Carbon $created_at
     */
    public function setCreatedAt(Carbon $created_at): void
    {
        $this->created_at = $created_at;
    }

    /**
     * @return string
     */
    public function getHomePlayerName(): string
    {
        return $this->home_player_name;
    }

    /**
     * @param string $home_player_name
     */
    public function setHomePlayerName(string $home_player_name): void
    {
        $this->home_player_name = $home_player_name;
    }

    /**
     * @return string
     */
    public function getHomePlayerRank(): string
    {
        return $this->home_player_rank;
    }

    /**
     * @param string $home_player_rank
     */
    public function setHomePlayerRank(string $home_player_rank): void
    {
        $this->home_player_rank = $home_player_rank;
    }

    /**
     * @return string
     */
    public function getVisitorPlayerName(): string
    {
        return $this->visitor_player_name;
    }

    /**
     * @param string $visitor_player_name
     */
    public function setVisitorPlayerName(string $visitor_player_name): void
    {
        $this->visitor_player_name = $visitor_player_name;
    }

    /**
     * @return string
     */
    public function getVisitorPlayerRank(): string
    {
        return $this->visitor_player_rank;
    }

    /**
     * @param string $visitor_player_rank
     */
    public function setVisitorPlayerRank(string $visitor_player_rank): void
    {
        $this->visitor_player_rank = $visitor_player_rank;
    }

    /**
     * @return string
     */
    public function getHomePlayer2Name(): ?string
    {
        return $this->home_player2_name;
    }

    /**
     * @param string $home_player2_name
     */
    public function setHomePlayer2Name(?string $home_player2_name): void
    {
        $this->home_player2_name = $home_player2_name;
    }

    /**
     * @return string
     */
    public function getVisitorPlayer2Name(): ?string
    {
        return $this->visitor_player2_name;
    }

    /**
     * @param string $visitor_player2_name
     */
    public function setVisitorPlayer2Name(?string $visitor_player2_name): void
    {
        $this->visitor_player2_name = $visitor_player2_name;
    }

    /**
     * @return string
     */
    public function getHomePlayer2Rank(): ?string
    {
        return $this->home_player2_rank;
    }

    /**
     * @param string $home_player2_rank
     */
    public function setHomePlayer2Rank(?string $home_player2_rank): void
    {
        $this->home_player2_rank = $home_player2_rank;
    }

    /**
     * @return string
     */
    public function getVisitorPlayer2Rank(): ?string
    {
        return $this->visitor_player2_rank;
    }

    /**
     * @param string $visitor_player2_rank
     */
    public function setVisitorPlayer2Rank(?string $visitor_player2_rank): void
    {
        $this->visitor_player2_rank = $visitor_player2_rank;
    }

    /**
     * @return Carbon
     */
    public function getUpdatedAt(): Carbon
    {
        return $this->updated_at;
    }

    /**
     * @param Carbon $updated_at
     */
    public function setUpdatedAt(Carbon $updated_at): void
    {
        $this->updated_at = $updated_at;
    }

    public function isSimple(): bool
    {
        return $this->getType() === self::TYPE_SIMPLE;
    }

    public function isDouble(): bool
    {
        return $this->getType() === self::TYPE_DOUBLE;
    }
}

bolt/src/Asmb/Competition/templates/championship/matches_sheet/_match_row.twig
{% set homePlayerIsWinner = matchesSheet.score|slice(0,1) == 'V' %}
<tr>
    <td class="has-text-weight-bold has-text-nowrap">{{ matchesSheet.label }}</td>

    <td>
        <div class="has-text-nowrap">
            <span class="player-name{{ homePlayerIsWinner ? ' has-text-weight-bold':'' }}">{{ matchesSheet.homePlayerName }}</span>
            <span class="rank is-block">({{ matchesSheet.homePlayerRank }})</span>
        </div>

        {% if matchesSheet.homePlayer2Name is not empty %}
            <div class="has-text-nowrap">
                <span class="player-name{{ homePlayerIsWinner ? ' has-text-weight-bold':'' }}">{{ matchesSheet.homePlayer2Name }}</span>
                <span class="rank is-block">({{ matchesSheet.homePlayer2Rank }})</span>
            </div>
        {% endif %}
    </td>

    <td class="text-center">{{ _self.renderScoreHtml(poolMeeting, matchesSheet, homePlayerIsWinner) }}</td>

    <td>
        <div class="has-text-nowrap">
            <span class="player-name{{ homePlayerIsWinner ? '':' has-text-weight-bold' }}">{{ matchesSheet.visitorPlayerName }}</span>
            <span class="rank is-block">({{ matchesSheet.visitorPlayerRank }})</span>
        </div>

        {% if matchesSheet.visitorPlayer2Name is not empty %}
            <div class="has-text-nowrap">
                <span class="player-name{{ homePlayerIsWinner ? '':' has-text-weight-bold' }}">{{ matchesSheet.visitorPlayer2Name }}</span>
                <span class="rank is-block">({{ matchesSheet.visitorPlayer2Rank }})</span>
            </div>
        {% endif %}
    </td>
</tr>

{# MACRO de rendu du score dans une ligne de feuille de match #}
{% macro renderScoreHtml(poolMeeting, matchesSheet, homePlayerIsWinner) %}
    {# on extrait les scores par set et par joueur ici #}
    {% set setsScores = matchesSheet.score|slice(2) %}
    {% set setParts = setsScores|split(' ') %}

    {% set isPlayerClubVictory = poolMeeting.homeTeamIsClub and homePlayerIsWinner or poolMeeting.visitorTeamIsClub and not homePlayerIsWinner %}
    {% set isPlayerClubDefeat = poolMeeting.homeTeamIsClub and not homePlayerIsWinner or poolMeeting.visitorTeamIsClub and homePlayerIsWinner %}

    <div class="columns is-multiline is-gapless is-size-6 score{{ isPlayerClubVictory ? ' victory':'' }}{{ isPlayerClubDefeat ? ' defeat':'' }}">
        {% for i in 0..2 %}
            <div class="column is-12">
                {% if setParts[i] is defined %}
                    {% set setScoreParts = setParts[i]|split('/') %}

                    {% if setScoreParts|length == 2 %}
                        {% set homeSetScore = setScoreParts[0] %}
                        {% set visitorSetScore = setScoreParts[1] %}

                        {% if homeSetScore > visitorSetScore %}
                            <strong>{{ homeSetScore }}</strong> / {{ visitorSetScore }}
                        {% elseif visitorSetScore > homeSetScore %}
                            {{ homeSetScore }} / <strong>{{ visitorSetScore }}</strong>
                        {% else %}
                            {{ homeSetScore }} / {{ visitorSetScore }}
                        {% endif %}

                        {% if setParts[i+1] is defined and setParts[i+1] == 'Ab.' %}
                            <span>Ab.</span>
                        {% endif %}
                    {% else %}
                        &nbsp;
                    {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endmacro %}

bolt/src/Asmb/Competition/templates/championship/matches_sheet/index.twig
{% extends 'partials/_master.twig' %}

{% set matchesSheetsCount = matchesSheets|length %}

{% block main %}
<section class="section section-competition section-championship">
    <div class="container">
        <h1 class="title is-size-1 is-size-3-mobile">{{ championship.fullName }}</h1>

        <div class="columns is-multiline">
            <div class="column is-12">
                <h2 class="title">{{ poolMeeting.categoryName }} &bullet; {{ pool.name }}</h2>
            </div>

            <div class="column is-12 is-8-desktop is-offset-2-desktop">
                <table class="table is-responsive is-fullwidth has-background-grey-lighter">
                    <thead>
                    <tr>
                        <th colspan="4">
                            <div class="columns is-gapless has-background-grey-lighter is-vcentered">
                                <div class="column is-5 is-size-4 text-secondary text-right">{{ poolMeeting.homeTeamName }}</div>
                                <div class="column is-2 is-size-4 text-center">
                                    {{ poolMeeting|score(true) }}
                                </div>
                                <div class="column is-5 is-size-4 text-secondary">{{ poolMeeting.visitorTeamName }}</div>
                            </div>
                        </th>
                    </tr>
                    <tr>
                        <th colspan="4">
                            <div class="columns is-gapless has-background-grey-lighter is-vcentered">
                                <div class="column text-primary is-size-5 has-text-nowrap is-6">J{{ poolMeeting.day }} - {{ poolMeeting.finalDate|date('d/m/y') }}</div>
                                <div class="column text-right is-6">
                                    <a href="{{ pool|fftMatchesSheetUrl(poolMeeting) }}" target="_blank"
                                       title="Feuille de match sur Ten'Up" class="text-primary">
                                        Voir sur Ten'Up <i class="fas fa-external-link-square-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </th>
                    </tr>
                    </thead>

                    <tbody>
                    {# Affichage des matchs SIMPLES #}
                    {% set showDayColumn = true %}

                    {% for matchesSheet in matchesSheets %}
                        {% if matchesSheet.isSimple %}
                            {% include '@AsmbCompetition/championship/matches_sheet/_match_row.twig' with {
                                'matchesSheet': matchesSheet,
                                'showDayColumn': showDayColumn,
                                'matchesSheetsCount':  matchesSheetsCount
                            } %}

                            {% set showDayColumn = false %}
                        {% endif %}
                    {% endfor %}

                    {# Affichage du match de DOUBLE #}
                    {% for matchesSheet in matchesSheets %}
                        {% if matchesSheet.isDouble %}
                            {% include '@AsmbCompetition/championship/matches_sheet/_match_row.twig' with {
                                'matchesSheet': matchesSheet,
                                'showDayColumn': false
                            } %}
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{#    {{ dump(poolMeeting) }}#}
{% endblock main %}